b_row = sym('b_i');
beta_char = sym('b%d',[size(train_images,2),1]);
disp(1);
Sigmoid_array = sym('S%d',[size(train_images,1),1]);
disp(2);
pre_fun = sym('p%d',[size(train_images,1),1]);
disp(3);
fun = sym('f%d',[size(train_images,1),1]);
disp(4);
train_images_row = sym('t%d',[1,size(train_images,2)]);
disp(5);
Sigmoid_array_row = train_images_row*beta_char;
disp(6);
pre_fun_row = sigmoid(Sigmoid_array_row);
disp(7);
fun_row = pre_fun_row-b_row;
disp(8);
jacobian_matrix_fun_row = jacobian(fun_row,beta_char);
disp(9);
fun(1) = subs(fun_row,train_images_row,train_images(1,:));
disp(10);
fun(1) = subs(fun_row,b_row,b(1));
disp(11);
jacobian_matrix_fun = subs(jacobian_matrix_fun_row,train_images_row,train_images(1,:));
disp(12);
jacobian_matrix_fun = subs(jacobian_matrix_fun_row,b_row,b(1));
disp(13);